### ISSUE TITLE
Full Stack Java Script courses to complete

### ISSUE THREAD

**Issue by leocast** [leocast/treehouse#2]
## TODO

_course left to complete in full stack javascript, Treehouse_
- [ ] Javascript Loops, Arrays and Objects
- [ ] jQuery Basics
- [ ] Using jQuery plugins
- [ ] Interactive Web Pages with Javascript
- [ ] Ajax Basics
- [ ] Object-Oriented Javascript
- [ ] Node.js Basics
- [ ] build a simple Dynamic Site with Node.js
- [ ] npm Basics
- [ ] Express Basics
- [ ] Gulp Basics
- [ ] Angular Basics
- [ ] Mongo Basics

cc @bandtasy

**Comment by leocast** [comment]
TODO

course left to complete in full stack javascript, Treehouse

* [ ] Javascript Loops, Arrays and Objects
* [ ] jQuery Basics
* [ ] Using jQuery plugins
* [ ] Interactive Web Pages with Javascript
* [ ] Ajax Basics
* [ ] Object-Oriented Javascript
* [ ] Node.js Basics
* [ ] build a simple Dynamic Site with Node.js
* [ ] npm Basics
* [ ] Express Basics
* [ ] Gulp Basics
* [ ] Angular Basics
* [ ] Mongo Basics

cc @bandtasy
